### PR TITLE
clean up hs_wca

### PR DESCRIPTION
**Pull request by js850**
This removes a lot of redundant code.  Mostly they are sanity checks that can be done in common child or parent classes.

still to do is to compute rcut explicitly in the constructors in hs_wca.h.  Then they don't need to be passed from the cython level

### CODE REVIEW

**Comment by kjs73** [comment]
Looks good to me!
As an equality, this can be taken to compute r_cut:
```
rcut < 2 * (1 + sca) * *std::max_element(radii.begin(), radii.end())
```

**Comment by js850** [comment]
@kjs73  @smcantab  I removed the HS_WCA frozen c++ potentials and updated the cython file.  Can you guys check carefully that what I did was correct.

**Comment by smcantab** [comment]
ok I'll take a look

**Comment by smcantab** [comment]
nice it looks good! This is a much better design, thanks! I'll do the changes in basinvolume so that we can get rid of the rcut keyword. Also on https://github.com/js850/pele/blob/a6b058eb5fa51652c351ba08e3c9a29aaef18c4c/pele/potentials/_hs_wca_cpp.pyx#L100
shouldn't we raise an exception?why would you use a frozen potential without frozen atoms?

**Comment by kjs73** [comment]
Having an exception at
    https://github.com/js850/pele/blob/a6b058eb5fa51652c351ba08e3c9a29aaef18c4c/pele/potentials/_hs_wca_cpp.pyx#L100
would also be OK, I agree.
At least nothing wrong will happen I belive by using the frozen potential without frozen d.o.f. if it just prints the warning.

**Comment by smcantab** [comment]
yes but since the frozen potential is a wrapper, it's likely to just slow things down by adding an extra layer of indirection. Maybe when we test for frozen we can also test that the frozen array is not empty or None, in which case we don't wrap

**Comment by kjs73** [comment]
that is true!
in particular with the new design it should not happen that one uses the frozen wrapper without a frozen array unless it is a user mistake.

**Pull request merged**
