### PR TITLE
add exception tests

### PR DESCRIPTION
**Pull request by kjs73**

### CODE REVIEW

**Comment by js850** [comment]
These can be done using "EXPECT_THROW" or "ASSERT_THROW".  See

https://github.com/pele-python/pele/blob/master/cpp_tests/source/test_array.cpp#L157

**Comment by kjs73** [comment]
Cool! 
I did not know this existed.

**Comment by js850** [comment]
there are more assertions here

https://code.google.com/p/googletest/wiki/AdvancedGuide

**Comment by js850** [comment]
:+1:

**Pull request merged**
