### PR TITLE
Python3 2

### PR DESCRIPTION
**Pull request by farrelljd**
nosetests now pass for python2 and python3 EXCEPT for pele.mindist.tests.permutational_alignment_test.PermutationTest which requires Hungarian.

I have edited nothing outside of pele/pele (no changes to examples, etc).

### CODE REVIEW

**Comment by js850** [comment]
Thanks James, this is fantastic!

**Comment by smcantab** [comment]
Amazing! James did you use some automatic conversion tool? I'd also like to make my other libraries python 3 compatible.

⁣Sent from BlueMail ​

**Comment by farrelljd** [comment]
@js850 glad you like it
@smcantab I mostly used 2to3. print statements and absolute imports I did with futurize, but the latter required a lot of further processing. Some things I did by hand based on the failing tests, like __next__, None comparisons, etc.

**Comment by js850** [comment]
James, feel free to merge this pull request.

**Comment by farrelljd** [comment]
Awesome - how do I do that?

**Comment by js850** [comment]
Do you see a button on this page (near the bottom) labeled "Squash and merge"?  Click that.  If not I can do it for you.

**Comment by farrelljd** [comment]
Nope. I see "Only those with write access to this repository can merge pull requests." ;-)

**Pull request merged**
