### PR TITLE
Inverse power updates

### PR DESCRIPTION
**Pull request by kjs73**
Improve efficiency of current inverse power potential
Add new inverse power potential without cutoff

The new inverse power potential is intended to be the one used here:
http://dx.doi.org/10.1063/1.449840

### CODE REVIEW

**Comment by smcantab** [comment]
looks good, shall we add a couple of python test to keep track of whether the the wrapping breaks?

**Comment by kjs73** [comment]
OK, sounds good

**Comment by kjs73** [comment]
@smcantab is this what you were thinking of?

**Comment by smcantab** [comment]
looks good!

**Pull request merged**
