### PR TITLE
replace python LowestEigPotential with cpp version

### PR DESCRIPTION
**Pull request by smcantab**
I started this with the intent of getting rid of multiple implementations of the same things, namely the LowestEigPotential that is implemented both in python (for NEB) and c++ for aatopology. I wrapped the cpp classes in Cython but then realised that the two classes do slightly different things and it's not going to be so strightforward replacing the python one. Not a priority at the moment but I have done the work and will leave it here for feedback, future reference. Unfortunately I noticed that I dragged some changes from the pspin model, so I'll rebase this PR when I merge the pspin model changes.

### CODE REVIEW

**Comment by js850** [comment]
In what way do they do slightly different things?

**Comment by smcantab** [comment]
I gave it a second look and realised (I was still wrong) that they were doing the same thing, so I added the second order approximation for the curvature, no pushed. Then I looked at it again and realised that they are still different because of the way they orthogonalize the eigenvectors. The cpp implementation only orthogonalizes with respect to the translational symmetries as it is not implemented for rotational symmetries. The python implementation in addition can take a custom `orthogZeroEigs` function, how would we replace that functionality with minimal pain? Python uses the fortran `orthogopt`

**Comment by js850** [comment]
Hmm, I'm not sure it's worth it continuing here.  It would be nice to have only one implementation, but it's also nice to have purely python implementations as long as it's not too slow.

The fortran orthogopt function is sort of delicate.  It's one of those methods that's easy to write down but getting it to be numerically stable is not trivial.  

To make it fully flexible you would have to provide c++ and cython functionality to be able to pass arbitrary orthogonalize functions.  I just don't think it's worth it.

**Comment by smcantab** [comment]
I agree, it's a lot of work, and ultimately the python version is the most flexible. I'll close it for now, if we need a full cpp implementation in the future we can pick it up from here.

**Pull request closed without merging**
